### ISSUE TITLE
Question: Ability to fetch all branches in a project

### ISSUE THREAD

**Issue by thelinuxer** [OpenReplyDE/bbbackup#7]
Hi,

I was wondering if bbbackup can actually backup all branches in all projects and not just the master (main focus) branch. 

Thanks.

**Comment by or-staedtler** [comment]
I should right now be able to exactly that. thanks to contributors preparing a perfect merge, I was able to push the changes today. I actually wanted to do this right from the beginning.

Be careful, because now the download size may drastically increase. For us it was an increase by factor 3 times the GB over all approx. 300 repos.
